
# OBJS = nombre de objetos necesarios para la compilacion 
CPPFLAGS = -o # argumentos necesarios para la compilacion
# BINARY = nombre del programa principal(opcional)
# LDFLAGS = nombre de librerias externas



all:
	@echo "todavia no hace nada crack"


#esta regla compila el programa principal
holamundo:
	g++ $(CPPFLAGS) holamundo holamundo.cpp

hola2:
	g++ $(CPPFLAGS) hola2 hola2.cpp

cifras:
	g++ $(CPPFLAGS) cifras cifras.cpp

ej:
	g++ $(CPPFLAGS) ej ej.cpp


clean:
	@#se coloca @ para que no aparezca el comando
	@echo "todavia no se puede borrar nada crack"
